backend:
  replicaCount: 1
  image:
    repository: asia-south1-docker.pkg.dev/gke-learning-496915/batchops/batchops-backend
    tag: 2f2f498b425f24cf0827dcf00fd2b82107f54cc9
frontend:
  replicaCount: 1
  image:
    repository: asia-south1-docker.pkg.dev/gke-learning-496915/batchops/batchops-frontend
    tag: 2f2f498b425f24cf0827dcf00fd2b82107f54cc9
ingress:
  className: gce
  host: ""
imageUpdater:
  enabled: true
  applicationName: batchops-monitor
  git:
    repository: https://github.com/jalajmalhotra16/batchops-monitor.git
    branch: main
