backend:
  replicaCount: 1
  image:
    repository: asia-south1-docker.pkg.dev/gke-learning-496915/batchops/batchops-backend
    tag: 0d33199570286db24cf6be0480bfe4abb4b3c775

frontend:
  replicaCount: 1
  image:
    repository: asia-south1-docker.pkg.dev/gke-learning-496915/batchops/batchops-frontend
    tag: 0d33199570286db24cf6be0480bfe4abb4b3c775

ingress:
  className: gce
  host: ""

imageUpdater:
  enabled: true
  applicationName: batchops-monitor
  git:
    repository: https://github.com/jalajmalhotra16/batchops-monitor.git
    branch: main