apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: vm
spec:
  replicaCount: 1

  selectAllByDefault: true

  remoteWrite:
    - url: http://vmsingle-victoria.vm.svc:8429/api/v1/write

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi