apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: kubelet
  namespace: vm
spec:
  interval: 30s
  scrapeTimeout: 10s

  scheme: https

  bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token

  tlsConfig:
    insecureSkipVerify: true

  endpoints:
    - port: https-metrics
      path: /metrics

    - port: https-metrics
      path: /metrics/cadvisor

    - port: https-metrics
      path: /metrics/resource