{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
  namespace: {{ .Values.namespace }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.externalSecrets.secretStore.gcp.projectID }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.externalSecrets.secretStore.gcp.clusterLocation }}
          clusterName: {{ .Values.externalSecrets.secretStore.gcp.clusterName }}
          serviceAccountRef:
            name: {{ .Values.externalSecrets.secretStore.gcp.serviceAccountName }}
{{- end }}

---

{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.git.writeBack.secret.name  }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}

  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: SecretStore

  target:
    name: {{ .Values.git.writeBack.secret.name  }}
    creationPolicy: Owner

  data:
{{- range .Values.externalSecrets.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ $.Values.externalSecrets.remoteSecret.name }}
        property: {{ .property }}
{{- end }}
{{- end }}