apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: batchops-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}  # Number of pod replicas
  selector:
    matchLabels:
      app: batchops-frontend
  template:
    metadata:
      labels:
        app: batchops-frontend
    spec:
      containers:
        - name: batchops-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: IfNotPresent 
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "test"
            - name: VITE_API_URL
              value: "/api"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20

