{{- if .Values.imageUpdater.enabled }}
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: {{ .Values.imageUpdater.applicationName }}
  namespace: argocd

spec:
  applicationRefs:
    - namePattern: {{ .Values.imageUpdater.applicationName }}

      writeBackConfig:
        method: git
        gitConfig:
          branch: {{ .Values.imageUpdater.git.branch }}
          writeBackTarget: helmvalues:./values-gke.yaml

      commonUpdateSettings:
        updateStrategy: latest

      images:
        - alias: backend
          imageName: {{ .Values.backend.image.repository }}
          manifestTargets:
            helm:
              name: backend.image.repository
              tag: backend.image.tag

        - alias: frontend
          imageName: {{ .Values.frontend.image.repository }}
          manifestTargets:
            helm:
              name: frontend.image.repository
              tag: frontend.image.tag
{{- end }}