{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: argocd
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.externalSecrets.gcpProjectID }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.externalSecrets.clusterLocation }}
          clusterName: {{ .Values.externalSecrets.clusterName }}
          serviceAccountRef:
            name: {{ .Values.externalSecrets.serviceAccountName }}
{{- end }}

---

{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.secretName }}
  namespace: argocd
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.externalSecrets.gcpSecretName }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.gcpSecretName }}
        property: password
{{- end }}