apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updator
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://github.com/jalajmalhotra16/batchops-monitor.git
      targetRevision: main
      path: helm/argocd-image-updater/

      helm:
        valueFiles:
          - $values/gitops/apps/argocd-image-updater.yaml

    - repoURL: https://github.com/jalajmalhotra16/batchops-monitor.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true 