apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://github.com/jalajmalhotra16/batchops-monitor.git
      targetRevision: main
      path: helm/keda/

      helm:
        valueFiles:
          - $values/gitops/apps/keda.yaml

    - repoURL: https://github.com/jalajmalhotra16/batchops-monitor.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: keda

  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true