name: Build and Push Docker Images

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      ############################################################
      # Backend
      ############################################################

      - name: Build Backend Image
        run: |
          docker build \
            -t asia-south1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/batchops/batchops-backend:${{ github.sha }} \
            -t asia-south1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/batchops/batchops-backend:latest \
            .

      - name: Push Backend Image
        run: |
          docker push asia-south1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/batchops/batchops-backend:${{ github.sha }}
          docker push asia-south1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/batchops/batchops-backend:latest

      ############################################################
      # Frontend
      ############################################################

      - name: Build Frontend Image
        run: |
          docker build \
            -t asia-south1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/batchops/batchops-frontend:${{ github.sha }} \
            -t asia-south1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/batchops/batchops-frontend:latest \
            ./frontend

      - name: Push Frontend Image
        run: |
          docker push asia-south1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/batchops/batchops-frontend:${{ github.sha }}
          docker push asia-south1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/batchops/batchops-frontend:latest